name: Call Reusable Build

on:
  push:
    branches:
      - devops-practice
  workflow_dispatch:

jobs:
  call-build:
    uses: AshishReddyMandaa/demo-gab/.github/workflows/reusable-build.yml@devops-practice
    with:
      environment: "dev"
