name: Input Parameters Practice

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose the environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - production

      version:
        description: "Enter application version"
        required: true
        default: "1.0.0"
        type: string

      deploy:
        description: "Deploy application?"
        required: true
        default: false
        type: boolean

jobs:
  show-inputs:
    runs-on: ubuntu-latest

    steps:
      - name: Show Environment
        run: echo "Environment: ${{ inputs.environment }}"

      - name: Show Version
        run: echo "Version: ${{ inputs.version }}"

      - name: Show Deploy Choice
        run: echo "Deploy: ${{ inputs.deploy }}"

      - name: Deploy
        if: ${{ inputs.deploy }}
        run: echo "Deploying version ${{ inputs.version }} to ${{ inputs.environment }}"

      - name: Skip Deployment
        if: ${{ !inputs.deploy }}
        run: echo "Deployment skipped."
