name: Enterprise CI Pipeline 

 
# ─────────────────────────────────────────────
# Trigger
# ─────────────────────────────────────────────
on:
  push:
    branches:
      - main
      - master
      - develop
      - feature/**
  pull_request:
    branches:
      - main
      - master
      - develop
  workflow_dispatch:

# ─────────────────────────────────────────────
# Default Permissions (Least Privilege)
# ─────────────────────────────────────────────
permissions:
  contents: read
  security-events: write
  actions: read
  checks: write
  packages: write
  id-token: write

# ─────────────────────────────────────────────
# Prevent Parallel Builds
# ─────────────────────────────────────────────
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

# ─────────────────────────────────────────────
# Global Environment Variables
# ─────────────────────────────────────────────
env:
  NODE_VERSION: "22"
  IMAGE_NAME:  ${{ secrets.DOCKER_USER }}/zomato_new
  IMAGE_TAG: ${{ github.sha }}

jobs:

  # ───────────────────────────────────────────
  # JOB 1: Build React Application
  # ───────────────────────────────────────────
  build:
    name: Build React Application
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        shell: bash

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Verify Installed Packages
        run: npm ls || true

      - name: Run ESLint
        run: npm run lint

      - name: Run Unit Tests
        env:
          CI: true
        run: echo "code is tested"

      - name: deploy
        run: echo "code is deployed"



