name: Status Check Practice

on:
  push:
    branches:
      - devops-practice
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Successful Test
        run: |
          echo "Running tests..."
          echo "Tests passed"

      - name: Run Only If Previous Steps Succeeded
        if: success()
        run: echo "Previous steps succeeded."

      - name: Run Only If Something Failed
        if: failure()
        run: echo "Something failed."

      - name: Always Run
        if: always()
        run: echo "This step always runs."

      - name: Complete job
        run: echo "Status check practice completed successfully."
